name: MacOS 11.7 TON Desktop wallet compile
on: [push,pull_request,workflow_dispatch]
jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          path: wallet-desktop
      - name: Compile macos desktop wallet
        run: |
          cd wallet-desktop/auto-build/macos-11.7
          chmod +x compile.sh
          ./compile.sh
      - name: Find & copy binaries
        run: |
          mkdir artifacts
          chmod -R 777 wallet-desktop/auto-build/macos-11.7/wallet-desktop/out/Release/Wallet.app
          cp -R wallet-desktop/auto-build/macos-11.7/wallet-desktop/out/Release/Wallet.app artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-macos-desktop-wallet
          path: artifacts